(ert-deftest xenops-element-get ()
  (should (equal (xenops-element-get 'inline-math :ops)
                 (xenops-element-get 'block-math :ops)))
  (should (not (equal (xenops-element-get 'inline-math :delimiters)
                      (xenops-element-get 'block-math :delimiters)))))
