(ert-deftest xenops-util-first-index ()
  (should (equal (xenops-util-first-index '(nil))
                 nil))
  (should (equal (xenops-util-first-index '(nil))
                 nil))
  (should (equal (xenops-util-first-index '(1))
                 0))
  (should (equal (xenops-util-first-index '(nil 1))
                 1))
  (should (equal (xenops-util-first-index '(1 nil))
                 0))
  (should (equal (xenops-util-first-index '(nil nil 0 t))
                 2)))
