(setq xenops-test-svg
      "<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.3.5 -->
<svg height='1.992528pt' version='1.1' viewBox='-0.996264 -0.996264 1.992528 1.992528' width='1.992528pt' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>
<g id='page1' transform='matrix(1.253143 0 0 1.253143 0 0)'>
<rect fill='#ffffff' height='0' width='0' x='0' y='0'/>
</g>
</svg>")

(defun xenops-test-mock-org-create-formula-image (latex file &rest args)
  (with-temp-buffer
    (insert xenops-test-svg)
    (write-file file)))

(defun xenops-render--do-test (buffer-contents element-begin)
  (cl-letf (((symbol-function 'org-create-formula-image)
             #'xenops-test-mock-org-create-formula-image))
    (let ((xenops-cache-directory (make-temp-file "xenops-test-" 'dir)))
      (with-temp-buffer
        (insert buffer-contents)
        (latex-mode)
        (xenops-mode)
        (mark-whole-buffer)
        (xenops-apply 'render)
        (goto-char element-begin)
        (let ((element (xenops-parse-element-at-point)))
          (should (equal (plist-get element :type) 'math)))
        (let ((image (xenops-math-get-image-at-point)))
          (should (equal (image-property image :type) 'svg)))))))

(ert-deftest xenops-render--inline-math ()
  (xenops-render--do-test "123$e^{2i\\pi}$maths." 4))

(ert-deftest xenops-render--display-math ()
  (xenops-render--do-test
   "Hello.
\\begin{align*}
  e^{2i\\pi}
\\end{align*}
" 8))

(ert-deftest xenops-render--table ()
  (xenops-render--do-test
   "This is a table.
\\begin{tabular}{c||c|c|c|c|c|}
    & e & a & b & c & d\\\\
  \\hline
  \\hline
  e & e & a & b & c & d\\\\
  a & a & b & c & d & e\\\\
  b & b & c & d & e & a\\\\
  c & c & d & e & a & b\\\\
  d & d & e & a & b & c
\\end{tabular}\\\\
" 18))
